"""Repository-root path conventions for Project FORESIGHT.

All paths are derived from this file's location so the project works from
any working directory and never hard-codes absolute Windows paths.

Expected layout (repository root, currently named ``mini-foresight``)::

    data/raw/        official internship extracts (expected input locations)
    data/processed/  analysis-ready outputs (generated by the D1 pipeline)
    notebooks/       exploratory notebooks (legacy Mini + future FORESIGHT)
    src/             reusable source code (this package)
    app/             Streamlit planning dashboard (D5)
    service/         scoring service (D6)
    reports/         executive readout (D7)
"""

from pathlib import Path

# Repository root = parent of the src/ package directory.
REPO_ROOT = Path(__file__).resolve().parent.parent

# Data locations
DATA_RAW = REPO_ROOT / "data" / "raw"
DATA_PROCESSED = REPO_ROOT / "data" / "processed"

# Application / service / report / notebook locations
APP_DIR = REPO_ROOT / "app"
SERVICE_DIR = REPO_ROOT / "service"
REPORTS_DIR = REPO_ROOT / "reports"
NOTEBOOKS_DIR = REPO_ROOT / "notebooks"

# The four official FORESIGHT raw extracts (expected input filenames only).
# These files are NOT present yet and must NOT be generated or fabricated.
OFFICIAL_RAW_FILES = {
    "sales_daily": "sales_daily.csv",
    "sku_master": "sku_master.csv",
    "calendar": "calendar.csv",
    "inventory_snapshots": "inventory_snapshots.csv",
}

# Official FORESIGHT schemas from the Zidio engagement brief (data contract).
OFFICIAL_SCHEMAS = {
    "sales_daily": ("date", "sku_id", "units_sold", "revenue", "unit_price", "promo_flag"),
    "sku_master": ("sku_id", "category", "subcategory", "launch_date", "unit_cost", "list_price"),
    "calendar": ("date", "week", "month", "season", "is_holiday", "promo_event"),
    "inventory_snapshots": (
        "date", "sku_id", "on_hand_units", "on_order_units",
        "lead_time_days", "reorder_point",
    ),
}
